import * as React from "react";

import { useState } from "react";
import { fileToBase64 } from "@/lib/file_utils";

// boilerplate generated by shadcn
function Input({
  id,
  placeholder,
  className,
  type,
  accept,
  onEnter,
  disabled,
}) {
  const [input, setInput] = useState("");

  function handleKeyDown(event) {
    if (event.key === "Enter") {
      onEnter(input);
      setInput("");
    }
  }

  async function handleChange(event) {
    const input = event.target.value;
    setInput(input);
    if (type === "file") {
      const file = event.target.files[0];
      const fileAsBase64String = await fileToBase64(file);
      onEnter({ type: file.type, name: file.name, data: fileAsBase64String });
      setInput("");
    }
  }

  return (
    <input
      id={id}
      type={type}
      accept={accept}
      data-slot="input"
      placeholder={placeholder}
      value={input}
      className={className}
      disabled={disabled}
      onChange={handleChange}
      onKeyDown={handleKeyDown}
    />
  );
}

export { Input };
