import * as React from "react";

import { useState } from "react";

// boilerplate generated by shadcn
function Input({ placeholder, className, type, onEnter, disabled }) {
  const [input, setInput] = useState("");

  function handleKeyDown(event) {
    if (event.key === "Enter") {
      onEnter(input);
      setInput("");
    }
  }

  function handleChange(event) {
    setInput(event.target.value);
  }

  return (
    <input
      type={type}
      data-slot="input"
      placeholder={placeholder}
      value={input}
      className={className}
      disabled={disabled}
      onChange={handleChange}
      onKeyDown={handleKeyDown}
    />
  );
}

export { Input };
